Refactor MemEffAttention to support CU130 pytorch 2.9.1 xformer 0.0.33+c2407a6.d20251023
Solution for newer versions (e.g. CUDA 13.0, PyTorch 2.9.1, xFormers 0.0.33).
There may be a better approach, but this setup works for me on both older and newer systems.

Error befor:

File "A:\SD\ComfyUI_070_cu130\python_embeded\Lib\site-packages\xformers\ops\fmha\dispatch.py", line 83, in _run_priority_list
raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
query : shape=(1, 1370, 16, 64) (torch.float32)
key : shape=(1, 1370, 16, 64) (torch.float32)
value : shape=(1, 1370, 16, 64) (torch.float32)
attn_bias : <class 'NoneType'>
p : 0.0
`fa3F@0.0.0` is not supported because:
requires device with capability < (8, 0) but your GPU has capability (12, 0) (too new)
dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
operator wasn't built - see `python -m xformers.info` for more info
requires device with capability == (8, 0) but your GPU has capability (12, 0) (too new)
`fa2F@2.8.3` is not supported because:
dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
`cutlassF-pt` is not supported because:
requires device with capability < (5, 0) but your GPU has capability (12, 0) (too new)